/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoceTemDireitoRouteImport } from './routes/voce-tem-direito'
import { Route as TrabalhadorRuralRouteImport } from './routes/trabalhador-rural'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as QueroMeAposentarRouteImport } from './routes/quero-me-aposentar'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinksRouteImport } from './routes/links'
import { Route as GuiaDoBeneficioPorIncapacidadeRouteImport } from './routes/guia-do-beneficio-por-incapacidade'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BpcLoasRouteImport } from './routes/bpc-loas'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BeneficiosNegadosRouteImport } from './routes/beneficios-negados'
import { Route as AreasDeAtuacaoRouteImport } from './routes/areas-de-atuacao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'

const VoceTemDireitoRoute = VoceTemDireitoRouteImport.update({
  id: '/voce-tem-direito',
  path: '/voce-tem-direito',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalhadorRuralRoute = TrabalhadorRuralRouteImport.update({
  id: '/trabalhador-rural',
  path: '/trabalhador-rural',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const QueroMeAposentarRoute = QueroMeAposentarRouteImport.update({
  id: '/quero-me-aposentar',
  path: '/quero-me-aposentar',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaDoBeneficioPorIncapacidadeRoute =
  GuiaDoBeneficioPorIncapacidadeRouteImport.update({
    id: '/guia-do-beneficio-por-incapacidade',
    path: '/guia-do-beneficio-por-incapacidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BpcLoasRoute = BpcLoasRouteImport.update({
  id: '/bpc-loas',
  path: '/bpc-loas',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosNegadosRoute = BeneficiosNegadosRouteImport.update({
  id: '/beneficios-negados',
  path: '/beneficios-negados',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDeAtuacaoRoute = AreasDeAtuacaoRouteImport.update({
  id: '/areas-de-atuacao',
  path: '/areas-de-atuacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.index.lazy').then((d) => d.Route))
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.settings.lazy').then((d) => d.Route),
)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.messages.lazy').then((d) => d.Route),
)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.content.lazy').then((d) => d.Route))
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.blog.index.lazy').then((d) => d.Route),
)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.blog.new.lazy').then((d) => d.Route),
)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.blog.$id.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/beneficios-negados': typeof BeneficiosNegadosRoute
  '/blog': typeof BlogRouteWithChildren
  '/bpc-loas': typeof BpcLoasRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/guia-do-beneficio-por-incapacidade': typeof GuiaDoBeneficioPorIncapacidadeRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quero-me-aposentar': typeof QueroMeAposentarRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/trabalhador-rural': typeof TrabalhadorRuralRoute
  '/voce-tem-direito': typeof VoceTemDireitoRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/beneficios-negados': typeof BeneficiosNegadosRoute
  '/bpc-loas': typeof BpcLoasRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/guia-do-beneficio-por-incapacidade': typeof GuiaDoBeneficioPorIncapacidadeRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quero-me-aposentar': typeof QueroMeAposentarRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/trabalhador-rural': typeof TrabalhadorRuralRoute
  '/voce-tem-direito': typeof VoceTemDireitoRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog': typeof AdminBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/beneficios-negados': typeof BeneficiosNegadosRoute
  '/blog': typeof BlogRouteWithChildren
  '/bpc-loas': typeof BpcLoasRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/guia-do-beneficio-por-incapacidade': typeof GuiaDoBeneficioPorIncapacidadeRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quero-me-aposentar': typeof QueroMeAposentarRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/trabalhador-rural': typeof TrabalhadorRuralRoute
  '/voce-tem-direito': typeof VoceTemDireitoRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/areas-de-atuacao'
    | '/beneficios-negados'
    | '/blog'
    | '/bpc-loas'
    | '/contato'
    | '/equipe'
    | '/guia-do-beneficio-por-incapacidade'
    | '/links'
    | '/login'
    | '/politica-de-privacidade'
    | '/quero-me-aposentar'
    | '/servicos'
    | '/sobre'
    | '/termos-de-uso'
    | '/trabalhador-rural'
    | '/voce-tem-direito'
    | '/admin/content'
    | '/admin/messages'
    | '/admin/settings'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/areas-de-atuacao'
    | '/beneficios-negados'
    | '/bpc-loas'
    | '/contato'
    | '/equipe'
    | '/guia-do-beneficio-por-incapacidade'
    | '/links'
    | '/login'
    | '/politica-de-privacidade'
    | '/quero-me-aposentar'
    | '/servicos'
    | '/sobre'
    | '/termos-de-uso'
    | '/trabalhador-rural'
    | '/voce-tem-direito'
    | '/admin/content'
    | '/admin/messages'
    | '/admin/settings'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/blog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/areas-de-atuacao'
    | '/beneficios-negados'
    | '/blog'
    | '/bpc-loas'
    | '/contato'
    | '/equipe'
    | '/guia-do-beneficio-por-incapacidade'
    | '/links'
    | '/login'
    | '/politica-de-privacidade'
    | '/quero-me-aposentar'
    | '/servicos'
    | '/sobre'
    | '/termos-de-uso'
    | '/trabalhador-rural'
    | '/voce-tem-direito'
    | '/admin/content'
    | '/admin/messages'
    | '/admin/settings'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AreasDeAtuacaoRoute: typeof AreasDeAtuacaoRoute
  BeneficiosNegadosRoute: typeof BeneficiosNegadosRoute
  BlogRoute: typeof BlogRouteWithChildren
  BpcLoasRoute: typeof BpcLoasRoute
  ContatoRoute: typeof ContatoRoute
  EquipeRoute: typeof EquipeRoute
  GuiaDoBeneficioPorIncapacidadeRoute: typeof GuiaDoBeneficioPorIncapacidadeRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  QueroMeAposentarRoute: typeof QueroMeAposentarRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  TrabalhadorRuralRoute: typeof TrabalhadorRuralRoute
  VoceTemDireitoRoute: typeof VoceTemDireitoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voce-tem-direito': {
      id: '/voce-tem-direito'
      path: '/voce-tem-direito'
      fullPath: '/voce-tem-direito'
      preLoaderRoute: typeof VoceTemDireitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhador-rural': {
      id: '/trabalhador-rural'
      path: '/trabalhador-rural'
      fullPath: '/trabalhador-rural'
      preLoaderRoute: typeof TrabalhadorRuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quero-me-aposentar': {
      id: '/quero-me-aposentar'
      path: '/quero-me-aposentar'
      fullPath: '/quero-me-aposentar'
      preLoaderRoute: typeof QueroMeAposentarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-do-beneficio-por-incapacidade': {
      id: '/guia-do-beneficio-por-incapacidade'
      path: '/guia-do-beneficio-por-incapacidade'
      fullPath: '/guia-do-beneficio-por-incapacidade'
      preLoaderRoute: typeof GuiaDoBeneficioPorIncapacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bpc-loas': {
      id: '/bpc-loas'
      path: '/bpc-loas'
      fullPath: '/bpc-loas'
      preLoaderRoute: typeof BpcLoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios-negados': {
      id: '/beneficios-negados'
      path: '/beneficios-negados'
      fullPath: '/beneficios-negados'
      preLoaderRoute: typeof BeneficiosNegadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-de-atuacao': {
      id: '/areas-de-atuacao'
      path: '/areas-de-atuacao'
      fullPath: '/areas-de-atuacao'
      preLoaderRoute: typeof AreasDeAtuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AreasDeAtuacaoRoute: AreasDeAtuacaoRoute,
  BeneficiosNegadosRoute: BeneficiosNegadosRoute,
  BlogRoute: BlogRouteWithChildren,
  BpcLoasRoute: BpcLoasRoute,
  ContatoRoute: ContatoRoute,
  EquipeRoute: EquipeRoute,
  GuiaDoBeneficioPorIncapacidadeRoute: GuiaDoBeneficioPorIncapacidadeRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  QueroMeAposentarRoute: QueroMeAposentarRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  TrabalhadorRuralRoute: TrabalhadorRuralRoute,
  VoceTemDireitoRoute: VoceTemDireitoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
